repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3  # Check for the latest version: https://github.com/astral-sh/ruff-pre-commit/releases
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/jazzband/pip-tools
    rev: 7.4.1  # Or the latest release
    hooks:
      - id: pip-compile
        args: [--generate-hashes]
        files: ^requirements/.*\.in$

  - repo: local
    hooks:
      - id: uv-lock
        name: uv lock
        entry: uv lock
        language: system
        types: [python]
        pass_filenames: false

      - id: uv-export
        name: uv export
        entry: sh -c 'uv export --format=requirements-txt > requirements.txt'
        language: system
        types: [python]
        pass_filenames: false