# BASIC CONFIGURATION - DO NOT ALTER
# Put your configuration in `config.local.yaml`
# ########################################
# VIMEO
# ########################################
---
vimeo:
  client_id: ""
  client_secret: ""
  access_token: ""
# ########################################
# ########################################
dirs:
  work_dir: "./_tmp"
  video_dir: "./_tmp/videos"
# ########################################
# # GOOGLE SHEETS
# ########################################
spreadsheets:
  # Google Spreadsheet mapping room: id
  ids:
    room: "google-id"
  # Google Sheet names as a list
  sheets:
    - "Sheet 1"
# ########################################
# Pretalx
pretalx:
  event_slug: "pretalx-uri-slug"
  # Videos need to be split between the PyCon DE and PyData YouTube channels
  video_to_track:
    CODE: "Track"
  # identify the channel by track name or snippet
  track_to_channel:
    pycon: "pycon"
    pydata: "pydata"
  questions_map:
    # attribute: id
    # attributes must exist in SpeakerInfo data class
    some_attribute: 0
# ########################################
# Event
event:
  name: "PyCon DE & PyData Berlin 2024"
  url: "https://2024.pycon.de"
  program_url: "https://2024.pycon.de/program/"
# ########################################
# Local path to content images
session_images: ""
# ########################################
# ########################################
# YouTube
# ########################################
youtube:
  client_secrets_file: "client_secrets.json"
  api_key: ""
  max_description_length: 5000
  token_path: "./_secret/youtube_token.json"
# ########################################
# LinkedIn
# ########################################
linkedin  :
  access_token: ""
  refresh_token: ""
  client_id: ""
  client_secret: ""
  company_id: ""
# ########################################
# MKDocs
# standard configuration used to manipulate social cards
mkdocs:
  social_cards:
    # relative paths from the repository root
    cache_dir: "./.cache/plugin/social"
    site_dir: "./site/assets/images/social"
  # convention, rename your logo accordingly
  logo_path: "./docs/assets/images/social_card_logo.png"
# ########################################
# # Prompts for descriptions
prompts:
  teaser: >
    You are an expert editor and your task is to write one short teaser sentence to encourage people to watch
    the video based on the title and text.  The teaser should be a short sentence that is catchy and engaging.
    Use a professional tone. Start with 'Watch'.
  # note there is a placeholder to instruct about the desired the length: {max_tokens}
  description: >
    You are an expert editor and your task is to create a continuous text with about {max_tokens} tokens.
    The text describes the talk and should be concise and informative please. Mention the speaker names,
    jobs and companies. Never use the verb 'delve'. Make sure only to mention jobs and companies
    if they are mentioned in the text. 

# ########################################
# ########################################