---
site_name: Py Tube
site_url: https://pioneershub.github.io/pytube/
site_author: Alexander Hendorf
site_description: >-
  Manage and release conference videos on YouTube using the talk and speaker information in Pretalx.
# Repository
repo_name: PioneersHub/PyTube
repo_url: https://github.com/PioneersHub/PyTube

#
nav:
  - index.md
  - installation.md
  - scripts.md
  - Metadata:
      - Pre-Processing: processing.md
      - Add Descriptions with NLP: openai.md
  - YouTube: youtube.md
  - Spread the Word:
      - LinkedIn: linkedin.md
      - Email: emails.md

theme:
  name: material
  icon:
    logo: fontawesome/brands/youtube
  language: en
  palette:
    primary: custom
  features:
    - navigation.instant
  site_url: https://pioneershub.github.io/PyTube/

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - stylesheets/extra.css

plugins:
  - social:
      cards_layout_options:
        background_color: "#ffffff"
        color: "#000000"
  - search
  - tags

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage

# Copyright
copyright: >
  Copyright &copy; 2024 Pioneers Hub gGmbH –
  <a href="#__consent">Change cookie settings</a>
