---
site_name: Py Tube
site_url: https://pioneershub.github.io/pytube/
site_author: Alexander Hendorf
site_description: >-
  Manage and release conference videos on YouTube using the talk and speaker information in Pretalx.
# Repository
repo_name: PioneersHub/pytube
repo_url: https://github.com/PioneersHub/pytube

#
nav:
  - index.md
  - installation.md
  - scripts.md
  - Metadata:
      - Pre-Processing: processing.md
      - Add Descriptions with NLP: openai.md
  - YouTube: youtube.md
  - Spread the Word:
      - LinkedIn: linkedin.md
      - Email: emails.md
  - License: license.md
  - Pioneers Hub website: https://pioneershub.org/

theme:
  name: material
  icon:
    logo: fontawesome/brands/youtube
  language: en
  palette:
    primary: custom
  features:
    - navigation.instant
  site_url: https://pioneershub.github.io/pytube/

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "¤"
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


extra_css:
  - stylesheets/extra.css

plugins:
  - social:
      cards_layout_options:
        background_color: "#ffffff"
        color: "#000000"
  - search
  - tags
  - glightbox
  - open-in-new-tab

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage
  version:
    provider: mike
    default: stable
  # custom config for social cards customisation
  social_cards:
    dirs:
      # relative paths from the repository root
      cache_dir: "./.cache/plugin/social"
      site_dir: "./site/assets/images/social"
      # convention, rename your logo accordingly
    logo_path: "./docs/assets/images/social_card_logo.png"

hooks:
  - scripts/hook_copyright_year.py
  - scripts/hook_add_logo_to_social_cards.py

# Copyright
copyright: >
  Copyright &copy; 2024 Pioneers Hub gGmbH –
  <a href="#__consent">Change cookie settings</a>
