"""
Class to create records i.e., create one record file for each session with all metadata.

This file can be used for multiple use cases like:
- Create YouTube description
- Create posts on Social Media
- etc.
"""

import json
from contextlib import suppress
from pathlib import Path

from httpx import QueryParams
from pytanis import PretalxClient
from pytanis.pretalx.models import Submission

from manager import conf, logger
from manager.config import get_event_dir
from manager.handlers import sized_text, summary_from_transcript, teaser_text
from manager.models.sessions import Organization, PretalxSession, SessionRecord, SpeakerInfo
from manager.utils.common import SafeConfig, ensure_directory, load_json, save_json


def unmangle_submission_type(data: dict) -> dict:
    """Restore the pre-validation shape of ``submission_type``.

    pytanis' ``Submission.mangle_submission_type`` validator is not idempotent: it
    replaces the submission_type object by its ``name``. Validating already-stored
    (i.e. already mangled) session data a second time therefore hits
    ``getattr(<MultiLingualStr>, "name", None)`` and silently nulls the field, which
    makes the resulting record unloadable. Re-nest the value so the validator can
    unwrap it correctly again.
    """
    submission_type = data.get("submission_type")
    submission_type_id = data.get("submission_type_id")
    if isinstance(submission_type, dict) and "name" not in submission_type and isinstance(submission_type_id, int):
        return {**data, "submission_type": {"id": submission_type_id, "name": submission_type}}
    return data


def load_session_record(path: Path) -> SessionRecord:
    """Load a SessionRecord, keeping ``submission_type`` intact.

    Validating a stored record runs pytanis' non-idempotent
    ``mangle_submission_type`` again, which nulls the field (see
    ``unmangle_submission_type``). Anything that then writes the record back —
    ``add_descriptions``, the YouTube metadata step, the publisher — would persist
    that null and make the record permanently unloadable. Re-nesting the value
    before validation lets the validator unwrap it correctly instead.

    Use this everywhere instead of ``SessionRecord.model_validate_json``.
    """
    raw = json.loads(path.read_text())
    session = raw.get("pretalx_session", {}).get("session")
    if isinstance(session, dict):
        raw["pretalx_session"]["session"] = unmangle_submission_type(session)
    return SessionRecord.model_validate(raw)


def load_transcript(code: str, root: Path | None) -> str | None:
    """Return the transcript text for a talk, or None if unavailable.

    Layout: one folder per talk named with the 6-char Pretalx code, containing
    `transcript.md`. Matches the first directory whose name starts with the code.
    """
    if not root:
        return None
    for d in sorted(root.iterdir()):
        if d.is_dir() and d.name[:6] == code:
            transcript_file = d / "transcript.md"
            if transcript_file.exists():
                return transcript_file.read_text()
    return None


class Records:
    """
    Create and update records.
    Each session will have a record file with all metadata.
    The metadata is collected from the pretalx API (talks, speakers, etc.).
    Additional attributes are added to the record file like:
     - a teaser text
     - a short text, generated by GPT
     - a long text, generated by GPT
     - a linkable LinkedIn profile URL for tagging, if provided by the speaker
     - etc.

     The first step is to load all confirmed sessions from pretalx and store them in a JSON file:
     - load_all_confirmed_sessions(), load_all_speakers()
     This information is also used by other scripts in this module, e.g., to organize the video recordings.

     Further steps are optional and can be executed in any order. These steps will add or change the metadata on file:
        - adding teaser, short and long texts
        - extracting LinkedIn, GitHub and X profile URLs
    """

    def __init__(self, qmap: dict[str, int] | None = None, *, reload=False):
        """

        :param qmap: Some metadata can only be found in the answers to customs questions in Pretalx
        Custom questions are stored in a list of sub-documents in the pretalx session and speaker data.
        To identify the right questions, we need to map the question IDs to answer texts.
        The parameter qmap must be a dict like {attribute name to add to `SpeakerInfo` or `Organization`: ID}.
        :param reload:
        """
        self.qmap: dict[str, int] | None = qmap
        self.reload: bool = reload
        self.pretalx_client = PretalxClient()
        self._tracks_map: dict = {}
        self._confirmed_sessions_map: dict = {}
        self._speakers_map: dict = {}

        # Event-specific directories
        self.event_dir = get_event_dir(conf)
        self.records: Path = self.event_dir / "records"
        ensure_directory(self.records)

    def load_all_confirmed_sessions(self) -> None:
        """Load all confirmed talks from pretalx and store it into a single JSON file stored in event-specific directory"""
        logger.info("Loading all confirmed sessions")
        the_dir = self.event_dir / "pretalx"
        ensure_directory(the_dir)

        # Always clear old data to ensure fresh fetch
        logger.info("Clearing old session data...")
        for x in the_dir.glob("*.json"):
            x.unlink()
        map_file = self.event_dir / "confirmed_sessions_map.json"
        if map_file.exists():
            map_file.unlink()

        try:
            # Get ONLY confirmed submissions
            # Note: Removed questions="all" due to pytanis validation bug with option IDs
            safe_conf = SafeConfig(conf)
            event_slug = safe_conf.get("pretalx.event_slug", "")
            if not event_slug:
                logger.error("No event slug configured")
                raise RuntimeError("Event slug not configured in config")
            subs_count, subs = self.pretalx_client.submissions(
                event_slug,
                params=QueryParams(state="confirmed"),
            )
        except Exception as e:
            logger.error(f"Failed to fetch submissions from Pretalx: {e}")
            raise RuntimeError(f"Unable to connect to Pretalx API: {e}") from e

        if subs is None:
            logger.error("Pretalx API returned None for submissions")
            raise RuntimeError("Pretalx API returned no data. Please check your event slug and credentials.")

        logger.info(f"Loaded {subs_count} confirmed sessions")

        if subs_count == 0:
            logger.warning("No confirmed sessions found!")
            safe_conf = SafeConfig(conf)
            logger.warning(f"Event slug: {safe_conf.get('pretalx.event_slug', 'not configured')}")
            logger.warning("Please check that your event has confirmed sessions in Pretalx")

        logger.info("Writing confirmed sessions to disk")

        try:
            # Convert iterator to list to ensure we process all pages
            logger.info("Converting submissions iterator to list...")
            subs_list = list(subs)
            logger.info(f"Successfully loaded {len(subs_list)} submissions into memory")

            if len(subs_list) == 0:
                logger.error("No submissions were returned by the iterator!")
                raise RuntimeError("Pretalx API returned 0 submissions after processing")

            written_count = 0
            for idx, sub in enumerate(subs_list, 1):
                try:
                    sub_json = sub.model_dump_json(indent=4)
                    file_path = the_dir / f"{sub.code}.json"
                    file_path.write_text(sub_json)
                    written_count += 1
                    if idx % 10 == 0:
                        logger.info(f"Progress: {idx}/{len(subs_list)} sessions written...")
                except Exception as e:
                    logger.error(f"Failed to write submission {sub.code}: {e}")

            logger.info(f"Successfully wrote {written_count} session files")
        except TypeError as e:
            logger.error(f"Failed to iterate over submissions: {e}")
            raise RuntimeError(
                "Cannot iterate over submissions. The API may have returned an unexpected format."
            ) from e

        logger.info(f"Done: wrote {written_count} confirmed sessions to disk")
        self.create_confirmed_sessions_map()

    def load_all_speakers(self) -> None:
        """Load all speakers from pretalx and store it into a single JSON file stored in event-specific directory"""
        logger.info("Loading all speakers")
        the_dir = self.event_dir / "pretalx_speakers"
        ensure_directory(the_dir)

        # Always clear old data to ensure fresh fetch
        logger.info("Clearing old speaker data...")
        for x in the_dir.glob("*.json"):
            x.unlink()
        map_file = self.event_dir / "speaker_map.json"
        if map_file.exists():
            map_file.unlink()

        try:
            safe_conf = SafeConfig(conf)
            event_slug = safe_conf.get("pretalx.event_slug", "")
            if not event_slug:
                logger.error("No event slug configured")
                raise RuntimeError("Event slug not configured in config")
            subs_count, subs = self.pretalx_client.speakers(event_slug, params=QueryParams(**{"questions": "all"}))
        except Exception as e:
            logger.error(f"Failed to fetch speakers from Pretalx: {e}")
            raise RuntimeError(f"Unable to connect to Pretalx API: {e}") from e

        if subs is None:
            logger.error("Pretalx API returned None for speakers")
            raise RuntimeError("Pretalx API returned no data. Please check your event slug and credentials.")

        logger.info(f"Loaded {subs_count} speakers")
        logger.info("Writing speakers to disk")

        written_count = 0
        try:
            for idx, sub in enumerate(subs, 1):
                try:
                    sub_json = sub.model_dump_json(indent=4)
                    file_path = self.event_dir / "pretalx_speakers" / f"{sub.code}.json"
                    file_path.write_text(sub_json)
                    written_count += 1
                    if idx % 10 == 0:
                        logger.info(f"Progress: {idx} speakers processed, {written_count} written...")
                except Exception as e:
                    logger.error(f"Failed to write speaker {getattr(sub, 'code', 'unknown')}: {e}")
        except TypeError as e:
            logger.error(f"Failed to iterate over speakers: {e}")
            raise RuntimeError("Cannot iterate over speakers. The API may have returned an unexpected format.") from e

        logger.info(f"Done: wrote {written_count}/{subs_count} speakers to disk")

        # Verify that at least some speakers were written
        if written_count == 0:
            logger.error("No speakers were successfully written to disk!")
            logger.error("This usually indicates pytanis validation errors with the API response")
            raise RuntimeError(
                f"Failed to write any speakers to disk (0/{subs_count} succeeded). Check logs for validation errors."
            )
        elif written_count < subs_count:
            logger.warning(f"Only {written_count}/{subs_count} speakers were successfully written")

        self.create_speaker_map()

    def create_confirmed_sessions_map(self) -> None:
        """Create a mapping of all confirmed sessions form the data loaded via `load_all_confirmed_sessions`"""
        the_dir = self.event_dir / "pretalx"
        confirmed_map = {}
        for x in the_dir.glob("*.json"):
            data = load_json(x)
            confirmed_map[data["code"]] = data
        if not confirmed_map:
            logger.error("No confirmed sessions found, did you run `load_all_confirmed_sessions`?")
        save_json(confirmed_map, self.event_dir / "confirmed_sessions_map.json")
        logger.info("Created confirmed sessions map")

    def create_speaker_map(self) -> None:
        """Create a mapping of all confirmed sessions form the data loaded via `load_all_confirmed_sessions`"""
        the_dir = self.event_dir / "pretalx_speakers"
        confirmed_map = {}
        for x in the_dir.glob("*.json"):
            data = load_json(x)
            confirmed_map[data["code"]] = data
        if not confirmed_map:
            logger.error("No speakers found, did you run `load_all_speakers`?")
        save_json(confirmed_map, self.event_dir / "speaker_map.json")
        logger.info("Created confirmed speakers map")

    @property
    def confirmed_sessions_map(self) -> dict:
        if not self._confirmed_sessions_map:
            map_file = self.event_dir / "confirmed_sessions_map.json"
            if not map_file.exists():
                logger.error(f"Confirmed sessions map not found at {map_file}")
                return {}
            self._confirmed_sessions_map = load_json(map_file)
        return self._confirmed_sessions_map

    @property
    def speakers_map(self) -> dict:
        if not self._speakers_map:
            map_file = self.event_dir / "speaker_map.json"
            if not map_file.exists():
                logger.error(f"Speaker map not found at {map_file}")
                return {}
            self._speakers_map = load_json(map_file)
        return self._speakers_map

    def create_records(self) -> dict[str, int]:
        """Create records for all confirmed sessions.

        Returns:
            Dictionary with statistics: {"created": int, "updated": int, "total": int}
        """
        stats = {"created": 0, "updated": 0, "total": 0}
        total_sessions = len(self.confirmed_sessions_map)

        logger.info(f"Creating records for {total_sessions} confirmed sessions...")

        for idx, (code, data) in enumerate(self.confirmed_sessions_map.items(), 1):
            logger.info(f"[{idx}/{total_sessions}] Processing record for {code}...")
            was_created = self.create_record(code, data)
            stats["total"] += 1
            if was_created:
                stats["created"] += 1
            else:
                stats["updated"] += 1

        logger.info(f"Record creation complete: {stats['created']} new, {stats['updated']} updated")
        return stats

    def create_record(self, code: str, data: dict) -> bool:
        """Create a record for a single session exclusively from pretalx data.

        Args:
            code: Session code
            data: Session data from Pretalx

        Returns:
            True if record was newly created, False if it was updated
        """
        record_path = self.records / f"{code}.json"
        is_new = not record_path.exists()
        p_session = PretalxSession(
            pretalx_id=data["code"],
            title=data["title"],
            session=Submission.model_validate(unmangle_submission_type(data)),
            speakers=[x["code"] for x in data["speakers"]],
        )

        def get_answer_via_id(answers: list[dict], answer_id: int):
            # answer_id is always > 0
            if not answers:  # Handle None or empty list
                return ""
            rec: list[dict[str, str]] = [x for x in answers if x.get("question", {}).get("id", -1) == answer_id]
            if rec:
                answer = rec[0]["answer"]
                if isinstance(answer, str):
                    answer = answer.strip()
                return answer
            return ""  # Return empty string instead of None

        def add_attr(obj, qmap, answers):
            if not qmap:  # Handle None or empty qmap
                return obj
            for attr, qid in qmap.items():
                answer = get_answer_via_id(answers, qid)
                if answer:
                    if attr == "company":
                        answer = Organization(name=answer)
                    with suppress(Exception):
                        setattr(obj, attr, answer)
            return obj

        speakers = []
        for speaker_code in p_session.speakers:
            speaker_data = self.speakers_map.get(speaker_code)
            if not speaker_data:
                logger.warning(f"Speaker {speaker_code} not found in speakers map")
                continue
            s = SpeakerInfo.model_validate(speaker_data)
            # Ensure answers is a list, even if None or missing
            answers = speaker_data.get("answers") or []
            s = add_attr(s, self.qmap, answers)
            speakers.append(s)

        record = SessionRecord(
            pretalx_session=p_session,
            pretalx_id=p_session.pretalx_id,
            title=p_session.title,
            abstract=data["abstract"],
            description=data["description"],
            speakers=speakers,
            as_tweet="",
            sm_teaser_text="",
            sm_short_text="",
            sm_long_text="",
        )
        # Records don't have answers, so pass empty list
        add_attr(record, self.qmap, [])

        # pytanis' `mangle_submission_type` validator mutates the Submission in place
        # every time it runs, and running it twice nulls submission_type (see
        # `unmangle_submission_type`). Restore both fields from the source data so the
        # stored record stays loadable.
        record_data = json.loads(record.model_dump_json())
        session_data = record_data.get("pretalx_session", {}).get("session")
        if isinstance(session_data, dict):
            session_data["submission_type"] = data.get("submission_type")
            session_data["submission_type_id"] = data.get("submission_type_id")
        record_path.write_text(json.dumps(record_data, indent=4, ensure_ascii=False))

        if is_new:
            logger.debug(f"Created new record for {code}")
        else:
            logger.debug(f"Updated existing record for {code}")

        return is_new

    @staticmethod
    def _apply_descriptions(data: SessionRecord, replace: bool, transcripts_root: Path | None) -> bool:
        """Generate teaser/short/long texts for one record in place.

        If a transcript is available for the talk, the short/long descriptions are
        summarized from it; otherwise they use the abstract-based prompt. The teaser
        always uses the abstract-based prompt. Returns whether any text was (re)generated.
        """
        # noinspection PyUnresolvedReferences
        speakers = "\n".join([f"{s.name} ({s.job}\nbiography:\n{s.biography})" for s in data.speakers])
        info = f"title:{data.title}\nspeaker(s):\n{speakers}\ndescription:\n{data.abstract}\n{data.description}"

        need_teaser = not data.sm_teaser_text or replace
        need_short = not data.sm_short_text or replace
        need_long = not data.sm_long_text or replace

        if need_teaser:
            data.sm_teaser_text = teaser_text(info, max_tokens=50)

        transcript = load_transcript(data.pretalx_id, transcripts_root)
        if transcript:
            grounding = f"Title: {data.title}\nSpeakers: {', '.join(s.name for s in data.speakers)}"
            logger.info(f"Using transcript summary for {data.pretalx_id}")
            if need_short:
                data.sm_short_text = summary_from_transcript(transcript, grounding, max_tokens=300, max_words=90)
            if need_long:
                data.sm_long_text = summary_from_transcript(transcript, grounding, max_tokens=700, max_words=250)
        else:
            if need_short:
                data.sm_short_text = sized_text(info, max_tokens=100)
            if need_long:
                data.sm_long_text = sized_text(info, max_tokens=300)

        return need_teaser or need_short or need_long

    def add_descriptions(self, replace=False, progress_callback=None) -> dict[str, int]:
        """Add descriptions to all confirmed sessions.

        Args:
            replace: Whether to replace existing descriptions
            progress_callback: Optional callable invoked once per record as
                ``callback(current, total, code, title, status)`` where status is
                one of "start", "generated", "skipped" or "error". Generation takes
                tens of seconds per talk, so callers should report "start" to show
                which session is running.

        Returns:
            Dictionary with statistics: {"processed": int, "added": int, "skipped": int}
        """

        def report(idx, code, title, status):
            if progress_callback:
                progress_callback(idx, total_records, code, title, status)

        stats = {"processed": 0, "added": 0, "skipped": 0}
        records = list(self.records.glob("*.json"))
        total_records = len(records)

        logger.info(f"Adding AI-generated descriptions to {total_records} records...")

        # Optional transcript-based summaries: if `transcripts.dir` is set, talks that
        # have a transcript get a high-quality summary from it; others keep the
        # abstract-based description. A configured-but-missing dir is a config error.
        transcripts_dir = SafeConfig(conf).get("transcripts.dir", "")
        transcripts_root = Path(transcripts_dir).expanduser() if transcripts_dir else None
        if transcripts_root and not transcripts_root.is_dir():
            raise FileNotFoundError(f"transcripts.dir is set but not a directory: {transcripts_root}")
        if transcripts_root:
            logger.info(f"Transcript summaries enabled from {transcripts_root}")

        for idx, x in enumerate(records, 1):
            try:
                data = load_session_record(x)
            except Exception as e:
                stats["processed"] += 1
                stats["skipped"] += 1
                try:
                    jdata = load_json(x)
                    code = jdata.get("pretalx_id", x.stem)
                except Exception:
                    code = x.stem
                logger.error(f"Error adding descriptions to {code}: {e}")
                report(idx, code, "", "error")
                continue

            report(idx, data.pretalx_id, data.title, "start")
            descriptions_added = self._apply_descriptions(data, replace, transcripts_root)

            (self.records / f"{data.pretalx_id}.json").write_text(data.model_dump_json(indent=4))

            stats["processed"] += 1
            if descriptions_added:
                stats["added"] += 1
                logger.info(f"[{idx}/{total_records}] Added descriptions to {data.pretalx_id}")
                report(idx, data.pretalx_id, data.title, "generated")
            else:
                stats["skipped"] += 1
                logger.debug(f"[{idx}/{total_records}] Skipped {data.pretalx_id} (descriptions already exist)")
                report(idx, data.pretalx_id, data.title, "skipped")

        logger.info(f"Description generation complete: {stats['added']} added, {stats['skipped']} skipped")
        return stats
