"""Prepare YouTube metadata from Pretalx records and YouTube ID mapping."""

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader

from .config import load_config
from .logging import setup_logging
from .paths import WorkPaths


def load_youtube_mapping(mapping_file: Path) -> dict[str, str]:
    """Load the Pretalx ID to YouTube ID mapping."""
    with open(mapping_file) as f:
        return json.load(f)


def load_template(template_path: Path, template_name: str) -> str:
    """Load Jinja2 template from file."""
    env = Environment(loader=FileSystemLoader(template_path), autoescape=False, trim_blocks=True, lstrip_blocks=True)
    template = env.get_template(template_name)
    return template


def prepare_video_metadata(
    pretalx_record: dict[str, Any],
    youtube_id: str,
    template: Any,  # noqa: ARG001
    event_name: str = "PyCon DE & PyData 2025",
) -> dict[str, Any]:
    """Prepare metadata for a single video.

    Note: Description text generation will be handled by external service.
    This function prepares the structure and basic metadata.
    """
    # Extract speakers info
    speakers = []
    if "speakers" in pretalx_record:
        for speaker in pretalx_record["speakers"]:
            speakers.append(speaker.get("name", "Unknown"))

    # Get recording date if available
    recorded_date = "April 2025"  # Default
    if "slot" in pretalx_record and pretalx_record["slot"] and "start" in pretalx_record["slot"]:
        # Parse and format date
        try:
            date_str = pretalx_record["slot"]["start"]
            # Handle different date formats
            if "T" in date_str:  # ISO format
                dt = datetime.fromisoformat(date_str.replace("Z", "+00:00"))
                recorded_date = dt.strftime("%B %d, %Y")
        except Exception:
            pass

    # Prepare channel assignment
    channel = "pycon"  # Default
    if "track" in pretalx_record and pretalx_record["track"]:
        track_name = pretalx_record["track"].get("name", {}).get("en", "")
        if "PyData" in track_name:
            channel = "pydata"

    # Prepare metadata structure
    metadata = {
        "pretalx_id": pretalx_record["code"],
        "youtube_id": youtube_id,
        "channel": channel,
        "title": pretalx_record.get("title", ""),
        "speakers": speakers,
        "recorded_date": recorded_date,
        "event_name": event_name,
        # Placeholder for description - will be generated by external service
        "description_placeholder": {
            "abstract": pretalx_record.get("abstract", ""),
            "description": pretalx_record.get("description", ""),
            "speakers_info": pretalx_record.get("speakers", []),
        },
        # YouTube specific metadata
        "youtube_metadata": {
            "category_id": 28,  # Science & Technology
            "default_language": "en",
            "privacy_status": "unlisted",
            "license": "youtube",
            "embeddable": True,
            "tags": ["Python", "PyConDE", "PyData", "Programming", "Software Development", "Open Source"],
        },
    }

    # Add track-specific tags
    if "track" in pretalx_record and pretalx_record["track"]:
        track_name = pretalx_record["track"].get("name", {}).get("en", "")
        if "MLOps" in track_name:
            metadata["youtube_metadata"]["tags"].extend(["MLOps", "Machine Learning", "DevOps"])
        elif "Data" in track_name:
            metadata["youtube_metadata"]["tags"].extend(["Data Science", "Analytics"])
        elif "Web" in track_name:
            metadata["youtube_metadata"]["tags"].extend(["Web Development", "FastAPI", "Django"])

    return metadata


def prepare_youtube_metadata():
    """Main function to prepare YouTube metadata for all videos."""
    # Setup
    config = load_config()
    logger = setup_logging(module_name="prepare_youtube_metadata")
    paths = WorkPaths(config)

    logger.info("Starting YouTube metadata preparation")

    # Load YouTube ID mapping
    mapping_file = Path("_tmp/pyconde-pydata-2025/videos/pretalx_yt_map.json")
    if not mapping_file.exists():
        logger.error(f"YouTube ID mapping file not found: {mapping_file}")
        return

    youtube_mapping = load_youtube_mapping(mapping_file)
    logger.info(f"Loaded {len(youtube_mapping)} YouTube ID mappings")

    # Load template
    template_dir = Path("src/manager/templates")
    template_name = "youtube_2025.txt"
    template = load_template(template_dir, template_name)

    # Create output directory
    paths.get_path("youtube_metadata")

    # Process each mapped video
    processed = 0
    skipped = 0

    for pretalx_id, youtube_id in youtube_mapping.items():
        # Load Pretalx record
        record_file = paths.get_path("pretalx_records", f"{pretalx_id}.yaml")
        if not record_file.exists():
            logger.warning(f"Pretalx record not found for {pretalx_id}, skipping")
            skipped += 1
            continue

        try:
            record = paths.load_yaml("pretalx_records", f"{pretalx_id}.yaml")

            # Prepare metadata
            metadata = prepare_video_metadata(record, youtube_id, template, event_name="PyCon DE & PyData 2025")

            # Generate filename
            title_slug = record["title"][:50].replace(" ", "-").replace("/", "-")
            title_slug = "".join(c for c in title_slug if c.isalnum() or c in "-_")
            filename = f"{pretalx_id}-{title_slug}.yaml"

            # Save metadata
            paths.save_yaml(metadata, "youtube_metadata", filename)
            processed += 1

            if processed % 10 == 0:
                logger.info(f"Progress: {processed} videos processed")

        except Exception as e:
            logger.error(f"Error processing {pretalx_id}: {e}")
            skipped += 1

    logger.info(
        "YouTube metadata preparation complete", processed=processed, skipped=skipped, total=len(youtube_mapping)
    )

    # Save summary
    summary = {
        "timestamp": datetime.now(UTC).isoformat(),
        "total_mappings": len(youtube_mapping),
        "processed": processed,
        "skipped": skipped,
        "template_used": template_name,
    }
    paths.save_yaml(summary, "youtube_metadata", "_summary.yaml")


if __name__ == "__main__":
    prepare_youtube_metadata()
