"""Scan raw Vimeo recording filenames and emit a YAML mapping of
filename -> {room, day, period}.

The YAML is the source of truth consumed by process_talk_list.py. It is
meant to be hand-edited: fill in anything the scanner couldn't classify
(typos, unusual naming) and fix misclassifications.
"""

import re
from pathlib import Path

import polars as pl
import yaml

from manager import conf, logger

_DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]

_PERIOD_ALIASES: dict[str, list[str]] = {
    "Morning": ["Morning", "AM"],
    "Afternoon": ["Afternoon", "PM"],
}

_ROOM_ANNOTATION_RE = re.compile(r"\s*\[[^\]]*\]\s*")


def _load_rooms(sessions_csv: Path) -> list[str]:
    """Pretalx Room column, bracket-annotations stripped, sorted longest-first
    so that 'Merck Plenary (Spectrum)' is preferred over a bare 'Merck' match.
    """
    df = pl.read_csv(sessions_csv, infer_schema_length=0)
    raw = {r for r in df["Room"].drop_nulls().to_list() if r}
    return sorted({_ROOM_ANNOTATION_RE.sub("", r).strip() for r in raw}, key=len, reverse=True)


def _classify(filename: str, rooms: list[str]) -> dict[str, str] | None:
    """Return {room, day, period} or None if any piece can't be inferred."""
    lower = filename.lower()

    day = next((d for d in _DAYS if d.lower() in lower), None)

    room = next((r for r in rooms if r.lower() in lower), None)

    period = None
    for canonical, aliases in _PERIOD_ALIASES.items():
        if any(re.search(rf"\b{re.escape(a)}\b", filename, flags=re.IGNORECASE) for a in aliases):
            period = canonical
            break

    if not (day and room and period):
        return None
    return {"room": room, "day": day, "period": period}


def run(dry_run: bool = False, force: bool = False) -> Path | None:
    mapping_yaml = conf.pretalx.get("recording_mapping_yaml", "") if hasattr(conf, "pretalx") else ""
    if not mapping_yaml:
        raise ValueError(
            "pretalx.recording_mapping_yaml is not set. "
            "Add it to config.yaml / config_local.yaml — path where the generated mapping YAML will be written."
        )
    sessions_csv = conf.pretalx.get("sessions_csv", "")
    if not sessions_csv:
        raise ValueError("pretalx.sessions_csv is not set.")
    recordings_dir = conf.vimeo.raw_sources.download.get("output_dir", "")
    if not recordings_dir:
        raise ValueError("vimeo.raw_sources.download.output_dir is not set.")

    mapping_path = Path(mapping_yaml)
    if mapping_path.exists() and not force and not dry_run:
        raise FileExistsError(
            f"{mapping_path} already exists. Re-run with --force to overwrite (hand edits will be lost)."
        )

    recordings_path = Path(recordings_dir)
    filenames = sorted(p.name for p in recordings_path.glob("*.mp4"))
    if not filenames:
        raise RuntimeError(f"No .mp4 files in {recordings_path}.")

    rooms = _load_rooms(Path(sessions_csv))
    logger.info(f"Scanning {len(filenames)} filenames against {len(rooms)} rooms")

    classified: dict[str, dict[str, str]] = {}
    unclassified: list[str] = []
    for name in filenames:
        entry = _classify(name, rooms)
        if entry is None:
            unclassified.append(name)
        else:
            classified[name] = entry

    logger.info(f"Classified {len(classified)}/{len(filenames)}; unclassified: {len(unclassified)}")
    for name in unclassified:
        logger.warning(f"  unclassified: {name}")

    if dry_run:
        logger.info("--- Dry run; not writing ---")
        logger.info(yaml.safe_dump({"recordings": classified}, sort_keys=False, allow_unicode=True))
        return None

    mapping_path.parent.mkdir(parents=True, exist_ok=True)
    with mapping_path.open("w") as f:
        f.write(
            "# Generated by `pytube video map-recordings` — hand-edit for typos / corner cases.\n"
            "# Keys are .mp4 filenames in vimeo.raw_sources.download.output_dir.\n"
            "# period: Morning | Afternoon\n\n"
        )
        yaml.safe_dump(
            {"recordings": classified}, f, sort_keys=False, allow_unicode=True, default_flow_style=False
        )
        if unclassified:
            f.write("\n# Unclassified — fill these in by hand:\n")
            for name in unclassified:
                f.write(f'#   "{name}": {{room: ?, day: ?, period: ?}}\n')

    logger.info(f"Wrote mapping for {len(classified)} filenames to {mapping_path}")
    return mapping_path


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="Print mapping without writing.")
    parser.add_argument("--force", action="store_true", help="Overwrite existing mapping YAML.")
    args = parser.parse_args()
    run(dry_run=args.dry_run, force=args.force)
