"""Hand-fill metadata templates for per-video presentation boundaries.

Flow:

1. ``emit_templates`` iterates entries from ``processing_plan.yaml`` and writes
   one ``metadata_template.yaml`` per video with blank HH:MM:SS rows sized to
   the scheduled talk count from the mapping YAML.
2. An operator fills ``start_hh_mm_ss`` / ``end_hh_mm_ss`` by hand.
3. ``apply_templates`` reads each filled template, converts HH:MM:SS to the
   seconds-based :class:`~video_processor.models.VideoMetadata` shape, and
   writes ``metadata_manual.yaml`` next to the detector's ``metadata.yaml``.

The two files are separate on purpose: ``metadata.yaml`` stays the detector's
machine output; ``metadata_manual.yaml`` is the hand-authored override.
"""

import re
from copy import deepcopy
from datetime import timedelta
from pathlib import Path

import yaml
from pydantic import BaseModel, Field

from manager import logger
from video_processor.models import PresentationSegment, VideoMetadata

TEMPLATE_FILENAME = "metadata_template.yaml"
MANUAL_METADATA_FILENAME = "metadata_manual.yaml"
UNFILLED_PLACEHOLDER = "HH:MM:SS"
_HH_MM_SS_RE = re.compile(r"^(\d{2}):(\d{2}):(\d{2})$")
_SEXAGESIMAL_MAX = 59  # highest valid value for MM and SS components

_TEMPLATE_HEADER = (
    "# Hand-fill metadata template — convert with:\n"
    "#   uv run python -m video_processor.presentation_detector --apply-templates\n"
    "# Times are strict HH:MM:SS with leading zeros (e.g. 00:02:30).\n"
    f"# Rows left as \"{UNFILLED_PLACEHOLDER}\" are treated as unfilled and will fail --apply-templates.\n"
    "# title / scheduled_duration are read-only hints from the Pretalx mapping — ignored on apply.\n\n"
)

_MANUAL_HEADER = (
    "# Hand-authored presentation metadata — validated by video_processor.models.VideoMetadata.\n"
    "# Seconds fields are authoritative. Do not edit this file by hand; edit the paired\n"
    f"# {TEMPLATE_FILENAME} and re-run --apply-templates.\n\n"
)


class PresentationTemplateEntry(BaseModel):
    """One hand-fill row inside :class:`PresentationTemplate`.

    ``title`` and ``scheduled_duration`` are advisory hints mirrored from the
    Pretalx mapping so the operator knows which talk they're filling. Only
    the HH:MM:SS fields are consumed by the converter.
    """

    index: int = Field(ge=1)
    title: str | None = None
    scheduled_duration: str | None = None
    start_hh_mm_ss: str
    end_hh_mm_ss: str


class PresentationTemplate(BaseModel):
    """Shape of ``{video_folder}/metadata_template.yaml``."""

    input_video: str
    output_folder: str
    presentations: list[PresentationTemplateEntry]


def parse_hh_mm_ss(value: str) -> int:
    """Parse strict ``HH:MM:SS`` (with leading zeros, MM/SS ≤ 59) to seconds.

    Raises ``ValueError`` with the offending value so callers can add row context.
    """
    if not isinstance(value, str):
        raise ValueError(f"expected string HH:MM:SS, got {type(value).__name__}: {value!r}")
    if value == UNFILLED_PLACEHOLDER:
        raise ValueError(f"unfilled placeholder {UNFILLED_PLACEHOLDER!r}")
    m = _HH_MM_SS_RE.match(value)
    if not m:
        raise ValueError(f"not strict HH:MM:SS (need 2-digit components): {value!r}")
    hh, mm, ss = (int(g) for g in m.groups())
    if mm > _SEXAGESIMAL_MAX or ss > _SEXAGESIMAL_MAX:
        raise ValueError(f"minutes/seconds must be 00-{_SEXAGESIMAL_MAX}: {value!r}")
    return hh * 3600 + mm * 60 + ss


def _scheduled_duration_hint(row: dict) -> str | None:
    """Best-effort short string describing a schedule row's duration for the operator."""
    raw = row.get("Duration")
    if raw is None:
        return None
    return str(raw)


def _title_hint(row: dict) -> str | None:
    title = row.get("Proposal title") or row.get("title")
    return None if title is None else str(title)


def _build_template(plan: dict) -> PresentationTemplate:
    """Build an unfilled template from a processing-plan entry."""
    rows = plan.get("presentations") or []
    entries = [
        PresentationTemplateEntry(
            index=i + 1,
            title=_title_hint(row),
            scheduled_duration=_scheduled_duration_hint(row),
            start_hh_mm_ss=UNFILLED_PLACEHOLDER,
            end_hh_mm_ss=UNFILLED_PLACEHOLDER,
        )
        for i, row in enumerate(rows)
    ]
    return PresentationTemplate(
        input_video=str(plan["input_video"]),
        output_folder=str(plan["output_folder"]),
        presentations=entries,
    )


def emit_templates(
    plan_entries: list[dict],
    output_root: Path,
    *,
    force: bool = False,
) -> list[Path]:
    """Write one ``metadata_template.yaml`` per plan entry under ``output_root``.

    Never overwrites an existing template unless ``force=True`` — protects
    in-progress hand-editing. Returns the list of paths written (skipped files
    are not included).
    """
    written: list[Path] = []
    for plan in plan_entries:
        out_dir = output_root / str(plan["output_folder"])
        out_dir.mkdir(parents=True, exist_ok=True)
        target = out_dir / TEMPLATE_FILENAME
        if target.exists() and not force:
            logger.info(f"emit_templates: SKIP existing {target} (use --force-emit-templates to overwrite)")
            continue
        template = _build_template(plan)
        payload = template.model_dump()
        with target.open("w") as f:
            f.write(_TEMPLATE_HEADER)
            yaml.safe_dump(payload, f, sort_keys=False, allow_unicode=True, default_flow_style=False)
        rows = len(template.presentations)
        logger.info(f"emit_templates: wrote {rows} row(s) to {target}")
        written.append(target)
    return written


def _segments_from_template(template: PresentationTemplate, source: Path) -> list[PresentationSegment]:
    """Convert template rows to :class:`PresentationSegment`, enforcing monotonicity."""
    segments: list[PresentationSegment] = []
    prev_end: int | None = None
    for row in template.presentations:
        try:
            start = parse_hh_mm_ss(row.start_hh_mm_ss)
            end = parse_hh_mm_ss(row.end_hh_mm_ss)
        except ValueError as exc:
            raise ValueError(f"{source}: row index={row.index}: {exc}") from exc
        if end <= start:
            raise ValueError(
                f"{source}: row index={row.index}: end_hh_mm_ss ({row.end_hh_mm_ss}) "
                f"must be strictly after start_hh_mm_ss ({row.start_hh_mm_ss})"
            )
        if prev_end is not None and start < prev_end:
            raise ValueError(
                f"{source}: row index={row.index}: start ({row.start_hh_mm_ss}) overlaps "
                f"previous row's end ({timedelta(seconds=prev_end)!s})"
            )
        duration = end - start
        segments.append(
            PresentationSegment(
                index=row.index,
                start_seconds=start,
                end_seconds=end,
                duration_seconds=duration,
                start_timecode=str(timedelta(seconds=start)),
                end_timecode=str(timedelta(seconds=end)),
                duration=str(timedelta(seconds=duration)),
            )
        )
        prev_end = end
    return segments


def _load_template(path: Path) -> PresentationTemplate:
    with path.open() as f:
        raw = yaml.safe_load(f) or {}
    return PresentationTemplate(**raw)


def apply_templates(plan_entries: list[dict], output_root: Path) -> list[Path]:
    """Convert each filled ``metadata_template.yaml`` to ``metadata_manual.yaml``.

    Plans whose template is missing are logged and skipped so a partial batch
    doesn't block the rest. Plans whose template is malformed raise — an
    explicit error is better than silently producing a wrong cut list.
    Returns the list of ``metadata_manual.yaml`` paths written.
    """
    written: list[Path] = []
    for plan in plan_entries:
        video_dir = output_root / str(plan["output_folder"])
        template_path = video_dir / TEMPLATE_FILENAME
        if not template_path.exists():
            logger.warning(f"apply_templates: no template at {template_path} — skipping")
            continue
        template = _load_template(template_path)
        segments = _segments_from_template(template, template_path)
        metadata = VideoMetadata(video=deepcopy(plan), presentations_index=segments)
        target = video_dir / MANUAL_METADATA_FILENAME
        with target.open("w") as f:
            f.write(_MANUAL_HEADER)
            yaml.safe_dump(
                metadata.model_dump(), f, sort_keys=False, allow_unicode=True, default_flow_style=False
            )
        logger.info(f"apply_templates: wrote {len(segments)} segment(s) to {target}")
        written.append(target)
    return written
