"""YouTube metadata models for video updates."""

from typing import Any

from pydantic import BaseModel, Field

from models.youtube_metadata import YouTubeMetadataDefaults


class DescriptionPlaceholder(BaseModel):
    """Placeholder for description content to be generated by external service."""

    abstract: str = Field(default="", description="Talk abstract from Pretalx")
    description: str = Field(default="", description="Talk description from Pretalx")
    speakers_info: list[dict[str, Any]] = Field(default_factory=list, description="Speaker information")


class PreparedVideoMetadata(BaseModel):
    """Complete prepared metadata for a video, ready for YouTube update."""

    pretalx_id: str = Field(..., description="Pretalx session ID")
    youtube_id: str = Field(..., description="YouTube video ID")
    channel: str = Field(..., description="Target channel (pycon/pydata)")
    title: str = Field(..., description="Video title")
    speakers: list[str] = Field(default_factory=list, description="Speaker names")
    recorded_date: str = Field(..., description="Recording date")
    event_name: str = Field(..., description="Event name")
    description_placeholder: DescriptionPlaceholder = Field(
        ..., description="Content for external description generation"
    )
    youtube_metadata: YouTubeMetadataDefaults = Field(
        default_factory=YouTubeMetadataDefaults, description="YouTube-specific settings"
    )
