"""Prepare LinkedIn posts from release records.

This script reads release records (generated by text_generation module) and creates
influent-compatible YAML files for posting to LinkedIn.

IMPORTANT: Only prepares posts for videos that are already PUBLIC on YouTube.

Directory structure created:
    {work_dir}/{event}/linkedin_posts/
    ├── posts/           # Influent YAML files ready to post
    ├── images/          # Images for posts (symlinks or copies)
    └── metadata/        # Metadata about generated posts

Usage:
    # Prepare all posts (only for public videos)
    python -m src.pipeline.linkedin.prepare_posts --all

    # Prepare specific sessions
    python -m src.pipeline.linkedin.prepare_posts LRUKZQ 3CYZUH

    # Force regeneration
    python -m src.pipeline.linkedin.prepare_posts --all --force

    # Skip YouTube status check (for testing)
    python -m src.pipeline.linkedin.prepare_posts --all --skip-status-check
"""

import argparse
import json
import sys
from pathlib import Path

import structlog
import yaml
from googleapiclient.errors import HttpError
from jinja2 import Template

from pipeline.config import load_config
from pipeline.logger import setup_logging
from pipeline.paths import WorkPaths
from pipeline.text_generation.models import ReleaseRecord
from pipeline.youtube.auth import YouTubeAuth

from .models import LinkedInPost, LinkedInPostMetadata

logger = structlog.get_logger()


class LinkedInPostPreparer:
    """Prepare LinkedIn posts from release records."""

    def __init__(self, skip_status_check: bool = False):
        """Initialize the post preparer.

        Args:
            skip_status_check: Skip YouTube public status check (for testing)
        """
        self.config = load_config()
        self.paths = WorkPaths(self.config)
        self.skip_status_check = skip_status_check

        # LinkedIn configuration
        try:
            self.linkedin_config = self.config.linkedin
        except AttributeError as e:
            raise ValueError("linkedin configuration not found in config") from e

        # Setup YouTube authentication (for status checking)
        self.youtube_auth = None
        if not skip_status_check:
            try:
                client_secrets = Path(self.config.youtube.client_secrets_file).expanduser()
                token_path = Path(self.config.youtube.token_path).expanduser()
                self.youtube_auth = YouTubeAuth(client_secrets, token_path)
                logger.info("youtube_auth_initialized", status_check_enabled=True)
            except Exception as e:
                logger.warning("youtube_auth_failed", error=str(e), message="Will skip status check")
                self.skip_status_check = True

        # Setup directories
        self.linkedin_dir = self._get_linkedin_dir()
        self.posts_dir = self.linkedin_dir / "posts"
        self.images_dir = self.linkedin_dir / "images"
        self.metadata_dir = self.linkedin_dir / "metadata"

        for dir_path in [self.posts_dir, self.images_dir, self.metadata_dir]:
            dir_path.mkdir(parents=True, exist_ok=True)

        logger.info(
            "linkedin_preparer_initialized",
            linkedin_dir=str(self.linkedin_dir),
            skip_status_check=self.skip_status_check,
        )

    def _get_linkedin_dir(self) -> Path:
        """Get LinkedIn posts directory from config or default.

        Returns:
            Path to LinkedIn posts directory
        """
        try:
            influent_path = self.linkedin_config.influent_path
        except AttributeError:
            influent_path = ""

        if influent_path:
            return Path(influent_path)

        # Default: {work_dir}/{event}/linkedin_posts/
        return self.paths.event_dir / "linkedin_posts"

    def load_release_record(self, pretalx_id: str) -> ReleaseRecord | None:
        """Load release record for a session.

        Args:
            pretalx_id: Pretalx session ID

        Returns:
            ReleaseRecord if found, None otherwise
        """
        record_file = self.paths.event_dir / "release_records" / f"{pretalx_id}.json"
        if not record_file.exists():
            logger.warning("release_record_not_found", pretalx_id=pretalx_id, path=str(record_file))
            return None

        try:
            with record_file.open() as f:
                data = json.load(f)
            return ReleaseRecord(**data)
        except Exception as e:
            logger.error("failed_to_load_release_record", pretalx_id=pretalx_id, error=str(e))
            return None

    def is_video_public(self, youtube_id: str) -> bool:
        """Check if YouTube video is public.

        Args:
            youtube_id: YouTube video ID

        Returns:
            True if video is public, False otherwise
        """
        if self.skip_status_check:
            logger.debug("status_check_skipped", youtube_id=youtube_id)
            return True

        if not self.youtube_auth:
            logger.warning("youtube_auth_not_available", youtube_id=youtube_id)
            return False

        try:
            video = self.youtube_auth.get_video(youtube_id)
            privacy_status = video.get("status", {}).get("privacyStatus", "")

            is_public = privacy_status == "public"

            logger.info(
                "checked_video_status",
                youtube_id=youtube_id,
                privacy_status=privacy_status,
                is_public=is_public,
            )

            return is_public

        except HttpError as e:
            logger.error("youtube_api_error", youtube_id=youtube_id, error=str(e))
            return False
        except Exception as e:
            logger.error("video_status_check_failed", youtube_id=youtube_id, error=str(e))
            return False

    def _generate_hashtags(self, channel: str) -> str:
        """Generate hashtags for a post.

        Args:
            channel: YouTube channel (pycon or pydata)

        Returns:
            Formatted hashtags string
        """
        if not self.linkedin_config.hashtags.enabled:
            return ""

        tags = list(self.linkedin_config.hashtags.default)

        # Add channel-specific hashtags
        channel_lower = channel.lower() if channel else ""
        track_map = dict(self.linkedin_config.hashtags.track_map)
        if channel_lower in track_map:
            tags.extend(track_map[channel_lower])

        return " ".join([f"#{tag}" for tag in tags])

    def prepare_post(self, pretalx_id: str, force: bool = False) -> LinkedInPostMetadata | None:
        """Prepare LinkedIn post for a session.

        Args:
            pretalx_id: Pretalx session ID
            force: Force regeneration even if exists

        Returns:
            LinkedInPostMetadata if successful, None otherwise
        """
        # Check if already prepared
        yaml_file = self.posts_dir / f"{pretalx_id}.yaml"
        metadata_file = self.metadata_dir / f"{pretalx_id}.json"

        if yaml_file.exists() and not force:
            logger.info("post_already_prepared", pretalx_id=pretalx_id)
            if metadata_file.exists():
                with metadata_file.open() as f:
                    return LinkedInPostMetadata(**json.load(f))
            return None

        # Load release record
        release_record = self.load_release_record(pretalx_id)
        if not release_record:
            logger.error("cannot_prepare_without_release_record", pretalx_id=pretalx_id)
            return None

        # Extract data from release record
        pretalx_data = release_record.pretalx_data
        ai_summaries = release_record.ai_summaries
        youtube_data = release_record.media.youtube

        # Get YouTube ID from metadata
        youtube_id = youtube_data.get("id", "")
        if not youtube_id:
            logger.error("youtube_id_not_found", pretalx_id=pretalx_id)
            return None

        # IMPORTANT: Check if video is public before preparing post
        if not self.is_video_public(youtube_id):
            logger.info(
                "video_not_public_skipping",
                pretalx_id=pretalx_id,
                youtube_id=youtube_id,
                message="Video must be public on YouTube before posting to LinkedIn",
            )
            return None

        youtube_url = f"https://www.youtube.com/watch?v={youtube_id}"

        # Get channel for hashtags
        channel = youtube_data.get("channel", "")

        # Generate hashtags
        hashtags = self._generate_hashtags(channel)

        # Prepare post text using template
        template = Template(self.linkedin_config.post_template)
        post_text = template.render(
            title=pretalx_data["title"],
            teaser_text=ai_summaries.teaser_text,
            social_text=ai_summaries.social.text,
            youtube_url=youtube_url,
            hashtags=hashtags,
        )

        # Create LinkedIn post model
        linkedin_post = LinkedInPost(
            pretalx_id=pretalx_id,
            title=pretalx_data["title"],
            teaser_text=ai_summaries.teaser_text,
            social_text=ai_summaries.social.text,
            youtube_url=youtube_url,
            youtube_id=youtube_id,
            hashtags=hashtags,
            post_text=post_text,
            image_path=None,  # TODO: Add image support
        )

        # Create influent YAML
        self._create_influent_yaml(linkedin_post, yaml_file)

        # Save metadata
        metadata = LinkedInPostMetadata(
            pretalx_id=pretalx_id,
            yaml_path=str(yaml_file),
        )

        with metadata_file.open("w") as f:
            json.dump(metadata.model_dump(mode="json"), f, indent=2)

        logger.info("linkedin_post_prepared", pretalx_id=pretalx_id, yaml_file=str(yaml_file))

        return metadata

    def _create_influent_yaml(self, post: LinkedInPost, yaml_file: Path):
        """Create influent-compatible YAML file.

        Args:
            post: LinkedIn post data
            yaml_file: Path to write YAML file
        """
        influent_data = {"post": {"text": post.post_text}}

        # Add image if available
        if post.image_path:
            influent_data["post"]["image_path"] = post.image_path

        with yaml_file.open("w") as f:
            yaml.safe_dump(influent_data, f, default_flow_style=False, allow_unicode=True)

    def prepare_all(self, force: bool = False, limit: int | None = None) -> dict:
        """Prepare LinkedIn posts for all sessions.

        Only prepares posts for videos that are already public on YouTube.

        Args:
            force: Force regeneration even if exists
            limit: Maximum number to prepare

        Returns:
            Statistics dictionary with counts
        """
        stats = {
            "prepared": 0,
            "skipped_existing": 0,
            "skipped_not_public": 0,
            "failed": 0,
            "prepared_ids": [],
            "skipped_not_public_ids": [],
            "failed_ids": [],
        }

        # Get all release records
        release_records_dir = self.paths.event_dir / "release_records"
        if not release_records_dir.exists():
            logger.error("no_release_records_found", path=str(release_records_dir))
            return stats

        record_files = sorted(release_records_dir.glob("*.json"))

        if limit:
            record_files = record_files[:limit]

        logger.info(
            "starting_batch_prepare",
            total=len(record_files),
            limit=limit,
            force=force,
            skip_status_check=self.skip_status_check,
        )

        for i, record_file in enumerate(record_files, 1):
            pretalx_id = record_file.stem

            # Skip special files
            if pretalx_id.startswith("_"):
                continue

            logger.info("processing_session", index=i, total=len(record_files), pretalx_id=pretalx_id)

            # Check if already exists before processing
            yaml_file = self.posts_dir / f"{pretalx_id}.yaml"
            if yaml_file.exists() and not force:
                stats["skipped_existing"] += 1
                logger.debug("post_already_exists_skipping", pretalx_id=pretalx_id)
                continue

            try:
                result = self.prepare_post(pretalx_id, force=force)

                if result:
                    stats["prepared"] += 1
                    stats["prepared_ids"].append(pretalx_id)
                else:
                    # Check if video exists in release record to determine skip reason
                    release_record = self.load_release_record(pretalx_id)
                    if release_record:
                        youtube_id = release_record.media.youtube.get("id", "")
                        if youtube_id:
                            # Has YouTube ID but not public - track separately
                            stats["skipped_not_public"] += 1
                            stats["skipped_not_public_ids"].append(pretalx_id)
                        else:
                            stats["failed"] += 1
                            stats["failed_ids"].append(pretalx_id)
                    else:
                        stats["failed"] += 1
                        stats["failed_ids"].append(pretalx_id)

            except Exception as e:
                logger.error("batch_prepare_error", pretalx_id=pretalx_id, error=str(e))
                stats["failed"] += 1
                stats["failed_ids"].append(pretalx_id)

        return stats


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Prepare LinkedIn posts from release records (only for public videos)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Prepare all LinkedIn posts (only for public videos)
  python -m src.pipeline.linkedin.prepare_posts --all

  # Prepare specific sessions
  python -m src.pipeline.linkedin.prepare_posts LRUKZQ 3CYZUH

  # Force regeneration
  python -m src.pipeline.linkedin.prepare_posts --all --force

  # Skip YouTube status check (for testing)
  python -m src.pipeline.linkedin.prepare_posts --all --skip-status-check

  # Limit for testing
  python -m src.pipeline.linkedin.prepare_posts --all --limit 5

Note:
  By default, this only prepares posts for videos that are PUBLIC on YouTube.
  Videos that are private/unlisted will be skipped with a message.
        """,
    )
    parser.add_argument("pretalx_ids", nargs="*", help="Specific Pretalx IDs to process")
    parser.add_argument("--all", action="store_true", help="Process all sessions")
    parser.add_argument("--force", action="store_true", help="Force regeneration even if already exists")
    parser.add_argument("--skip-status-check", action="store_true", help="Skip YouTube public status check (for testing)")
    parser.add_argument("--limit", type=int, help="Limit number of posts to prepare")
    args = parser.parse_args()

    # Validate arguments
    if not args.all and not args.pretalx_ids:
        parser.error("Either specify Pretalx IDs or use --all")

    # Setup logging
    logger = setup_logging(module_name="linkedin.prepare_posts")

    # Initialize preparer
    try:
        preparer = LinkedInPostPreparer(skip_status_check=args.skip_status_check)
    except ValueError as e:
        logger.error("initialization_failed", error=str(e))
        print(f"\nError: {e}")
        return 1

    # Process posts
    if args.all:
        logger.info("preparing_all_posts", force=args.force, limit=args.limit)
        stats = preparer.prepare_all(force=args.force, limit=args.limit)

        logger.info(
            "batch_prepare_complete",
            prepared=stats["prepared"],
            skipped_existing=stats["skipped_existing"],
            skipped_not_public=stats["skipped_not_public"],
            failed=stats["failed"],
            failed_ids=stats["failed_ids"],
        )

        print(f"\n✅ Prepared {stats['prepared']} LinkedIn posts")
        if stats["skipped_existing"] > 0:
            print(f"⏭️  {stats['skipped_existing']} already existed (use --force to regenerate)")
        if stats["skipped_not_public"] > 0:
            print(f"🔒 {stats['skipped_not_public']} videos not public on YouTube yet:")
            for pretalx_id in stats["skipped_not_public_ids"][:10]:  # Show first 10
                print(f"    - {pretalx_id}")
            if len(stats["skipped_not_public_ids"]) > 10:
                print(f"    ... and {len(stats['skipped_not_public_ids']) - 10} more")
        if stats["failed"] > 0:
            print(f"⚠️  {stats['failed']} failed:")
            for pretalx_id in stats["failed_ids"]:
                print(f"    - {pretalx_id}")

    else:
        # Process specific IDs
        prepared = 0
        for pretalx_id in args.pretalx_ids:
            result = preparer.prepare_post(pretalx_id, force=args.force)
            if result:
                prepared += 1

        logger.info("prepare_complete", requested=len(args.pretalx_ids), prepared=prepared)

        if prepared > 0:
            print(f"\n✅ Prepared {prepared} LinkedIn posts")

    # Show next steps
    post_count = len(list(preparer.posts_dir.glob("*.yaml")))
    if post_count > 0:
        print(f"\n📝 {post_count} LinkedIn posts ready in {preparer.posts_dir}")
        print("\nNext steps:")
        print(f"  cd {preparer.linkedin_dir}")
        print(f"  influent --organization {preparer.linkedin_config.organization_name} post [filename.yaml]")
        print("\nOr use the publish script:")
        print("  python -m src.pipeline.linkedin.publish_posts --all")

    return 0


if __name__ == "__main__":
    sys.exit(main())
